#!/bin/bash
# J Baxter 01/2020
SYMM=" 19"
echo 'Running trun_all_options'
if [  "X$#" == "X4" ] ; then
	HKL_FILENAME=$1
	res_high=$2
	res_low=$3
	space_group="$4"
else
    echo
    echo "Usage: trunc_all_options <*.hkl file> (res high) (res low)"
    echo
    exit 1
fi
TMPHKL=tmp.hkl
OUTFILE1=$(echo $HKL_FILENAME | sed -e 's/\.hkl$/_old_truncate.mtz/')
OUTFILE2=$(echo $HKL_FILENAME | sed -e 's/\.hkl$/_new_truncate.mtz/')
OUTFILE3=$(echo $HKL_FILENAME | sed -e 's/\.hkl$/_phenix_massage.mtz/')
OUTFILE4=$(echo $HKL_FILENAME | sed -e 's/\.hkl$/_phenix.mtz/')
BASENAME=$(echo $HKL_FILENAME | sed -e 's/\.hkl$//')
############################################################################
## If using CrystFEL HKL...
############################################################################
#grep -v "^End of reflections" $HKL_FILENAME | grep -v "^Generated by CrystFEL" | grep -v "process_hkl" | grep -v "indexamajig " | grep -v "^partialator" | grep -v "^Audit information from stream" | grep -v "^Indexing methods selected" | grep -v "Re-indexed" | grep -v "ambigator" | grep -v "^/opt/pxsoft/crystfel/" > $TMPHKL
######################################
## Make hkl into an mtz
#echo "Running f2mtz.."
######################################
f2mtz HKLIN $TMPHKL HKLOUT tmp.mtz >> ${BASENAME}_f2mtz_out.html << EOF
CELL ${space_group}
SYMM ${SYMM}
SKIP 3
LABOUT H K L IMEAN SIGIMEAN
CTYPE  H H H J     Q
FORMAT '(3(F4.0,1X),F10.2,10X,F10.2)'
EOF
############################################################################
## If using DIALS MTZ (renamed as a .hkl)..
############################################################################
cp $HKL_FILENAME tmp.mtz
#######################################
### Old Truncate
echo "Old Truncate.."
#######################################
#
## Will calculates best estimante of F and I from the distribution of intensities in resolution shell. It tries to put them on an absolute scale busing the scale facotr in the wilson plot -- Ie negatives are NOT preserved.
#truncate HKLIN tmp.mtz HKLOUT $OUTFILE1 > ${BASENAME}_truncate.log << EOF # this is the old version of truncate
#truncate     YES
#anomalous     NO
#resolution  $res_high $res_low
#contents     H 1705     C 1128     N 304     O 328     S 10
#plot     OFF
#header BRIEF BATCH
#labin IMEAN=IMEAN SIGIMEAN=SIGIMEAN
#labout  F=F SIGF=SIGF IMEAN=I SIGIMEAN=SIGI
#falloff     yes     cone 30.0     PLTX
#NOHARVEST
#end
#EOF
######################################
## New Truncate
#echo "NewTruncate.."
######################################
#Truncate will use french and wilson based algorithum for scaling the b factors also does anisotrpoic scaling.
#ctruncate -mtzin tmp.mtz -mtzout $OUTFILE2 -colin '/*/*/[IMEAN,SIGIMEAN]' -nres 238 > ${BASENAME}_ctruncate.log
#######################################
### Phneix with its massage conversion
echo "Phenix massage.."
#######################################
phenix.reflection_file_converter tmp.mtz --mtz=$OUTFILE3 --non_anomalous --write_mtz_amplitudes --mtz_root_label=F  --massage_intensities --resolution=$res_high > ${BASENAME}_phenix_massage.log
phenix.xtriage file $OUTFILE3 > ${BASENAME}_phenix_massage.log

# Phneix using what should be french wilson
#phenix.reflection_file_converter tmp.mtz --mtz=$OUTFILE4 --non_anomalous --write_mtz_amplitudes --mtz_root_label=F  > ${BASENAME}_phenix.log
rm -f tmp.hkl PLOT
echo 'Complete'
